/usr/local/bin/node /Users/kleinen/mine/current/htw/studiengangssprecher/lehrplanung/19w/lehreinsatzplanungsparser/main.js
{
    Directory: {
        workbooks: [ '/xl/workbook.xml' ],
            sheets: [ '/xl/worksheets/sheet1.xml', '/xl/worksheets/sheet2.xml' ],
            charts: [],
            dialogs: [],
            macros: [],
            rels: [],
            strs: [ '/xl/sharedStrings.xml' ],
            comments: [],
            links: [],
            coreprops: [ '/docProps/core.xml' ],
            extprops: [ '/docProps/app.xml' ],
            custprops: [],
            themes: [ '/xl/theme/theme1.xml' ],
            styles: [ '/xl/styles.xml' ],
            vba: [],
            drawings: [],
            TODO: [],
            xmlns: 'http://schemas.openxmlformats.org/package/2006/content-types',
            calcchain: '/xl/calcChain.xml',
            sst: '/xl/sharedStrings.xml',
            style: '/xl/styles.xml',
            defaults: {
            xml: 'application/xml',
                rels: 'application/vnd.openxmlformats-package.relationships+xml'
        }
    },
    Workbook: {
        AppVersion: {
            appName: 'xl',
                appname: 'xl',
                lastEdited: '5',
                lastedited: '5',
                lowestEdited: '7',
                lowestedited: '7',
                rupBuild: '28125',
                rupbuild: '28125'
        },
        WBProps: {
            autoCompressPictures: false,
                allowRefreshQuery: false,
                backupFile: false,
                checkCompatibility: false,
                CodeName: '',
                date1904: false,
                defaultThemeVersion: 0,
                filterPrivacy: false,
                hidePivotFieldList: false,
                promptedSolutions: false,
                publishItems: false,
                refreshAllConnections: false,
                saveExternalLinkValues: true,
                showBorderUnselectedTables: true,
                showInkAnnotation: true,
                showObjects: 'all',
                showPivotChartFilter: false,
                updateLinks: 'userSet'
        },
        WBView: [ [Object] ],
            Sheets: [ [Object], [Object] ],
            CalcPr: {
            calcId: '140001',
                calcid: '140001',
                concurrentCalc: '0',
                concurrentcalc: '0',
                calcCompleted: 'true',
                calcMode: 'auto',
                calcOnSave: 'true',
                fullCalcOnLoad: 'false',
                fullPrecision: 'true',
                iterate: 'false',
                iterateCount: '100',
                iterateDelta: '0.001',
                refMode: 'A1'
        },
        Names: [ [Object], [Object] ],
            xmlns: 'http://schemas.openxmlformats.org/spreadsheetml/2006/main',
            Views: [ {} ]
    },
    Props: {
        LastAuthor: 'B Kleinen',
            LastPrinted: '2019-09-10T12:20:41Z',
            Author: 'Kathrin',
            CreatedDate: 2019-09-10T10:50:35.000Z,
            ModifiedDate: 2019-10-05T16:48:19.000Z,
            Application: 'Microsoft Macintosh Excel',
            AppVersion: '14.0300',
            Company: '',
            DocSecurity: '0',
            Manager: '',
            HyperlinksChanged: false,
            SharedDoc: false,
            LinksUpToDate: false,
            ScaleCrop: false,
            Worksheets: 2,
            SheetNames: [ 'Tabelle1', 'Blatt1' ]
    },
    Custprops: {},
    Deps: {},
    Sheets: {
        Tabelle1: {
            '!ref': 'A1:L106',
                A1: [Object],
                B1: [Object],
                C1: [Object],
                D1: [Object],
                E1: [Object],
                F1: [Object],
                G1: [Object],
                H1: [Object],
                I1: [Object],
                J1: [Object],
                K1: [Object],
                L1: [Object],
                A2: [Object],
                B2: [Object],
                C2: [Object],
                D2: [Object],
                E2: [Object],
                F2: [Object],
                G2: [Object],
                H2: [Object],
                I2: [Object],
                J2: [Object],
                K2: [Object],
                A3: [Object],
                B3: [Object],
                C3: [Object],
                D3: [Object],
                E3: [Object],
                F3: [Object],
                G3: [Object],
                H3: [Object],
                I3: [Object],
                J3: [Object],
                L3: [Object],
                A4: [Object],
                B4: [Object],
                C4: [Object],
                D4: [Object],
                E4: [Object],
                F4: [Object],
                G4: [Object],
                H4: [Object],
                I4: [Object],
                J4: [Object],
                L4: [Object],
                A5: [Object],
                B5: [Object],
                C5: [Object],
                D5: [Object],
                E5: [Object],
                F5: [Object],
                G5: [Object],
                H5: [Object],
                I5: [Object],
                J5: [Object],
                K5: [Object],
                L5: [Object],
                A6: [Object],
                B6: [Object],
                C6: [Object],
                D6: [Object],
                E6: [Object],
                F6: [Object],
                G6: [Object],
                H6: [Object],
                I6: [Object],
                J6: [Object],
                K6: [Object],
                L6: [Object],
                A7: [Object],
                B7: [Object],
                C7: [Object],
                D7: [Object],
                E7: [Object],
                F7: [Object],
                G7: [Object],
                H7: [Object],
                I7: [Object],
                J7: [Object],
                K7: [Object],
                L7: [Object],
                A8: [Object],
                B8: [Object],
                C8: [Object],
                D8: [Object],
                E8: [Object],
                F8: [Object],
                G8: [Object],
                H8: [Object],
                I8: [Object],
                J8: [Object],
                K8: [Object],
                L8: [Object],
                A9: [Object],
                B9: [Object],
                C9: [Object],
                D9: [Object],
                E9: [Object],
                F9: [Object],
                G9: [Object],
                H9: [Object],
                I9: [Object],
                J9: [Object],
                K9: [Object],
                L9: [Object],
                A10: [Object],
                B10: [Object],
                C10: [Object],
                D10: [Object],
                E10: [Object],
                F10: [Object],
                G10: [Object],
                H10: [Object],
                I10: [Object],
                J10: [Object],
                K10: [Object],
                A11: [Object],
                B11: [Object],
                C11: [Object],
                D11: [Object],
                E11: [Object],
                F11: [Object],
                G11: [Object],
                H11: [Object],
                I11: [Object],
                J11: [Object],
                K11: [Object],
                A12: [Object],
                B12: [Object],
                C12: [Object],
                D12: [Object],
                E12: [Object],
                F12: [Object],
                G12: [Object],
                H12: [Object],
                I12: [Object],
                J12: [Object],
                K12: [Object],
                A13: [Object],
                B13: [Object],
                C13: [Object],
                D13: [Object],
                E13: [Object],
                F13: [Object],
                G13: [Object],
                H13: [Object],
                I13: [Object],
                J13: [Object],
                K13: [Object],
                L13: [Object],
                A14: [Object],
                B14: [Object],
                C14: [Object],
                D14: [Object],
                E14: [Object],
                F14: [Object],
                G14: [Object],
                H14: [Object],
                I14: [Object],
                J14: [Object],
                K14: [Object],
                L14: [Object],
                A15: [Object],
                B15: [Object],
                C15: [Object],
                D15: [Object],
                E15: [Object],
                F15: [Object],
                G15: [Object],
                H15: [Object],
                I15: [Object],
                J15: [Object],
                K15: [Object],
                L15: [Object],
                A16: [Object],
                B16: [Object],
                C16: [Object],
                D16: [Object],
                E16: [Object],
                F16: [Object],
                G16: [Object],
                H16: [Object],
                I16: [Object],
                J16: [Object],
                K16: [Object],
                A17: [Object],
                B17: [Object],
                C17: [Object],
                D17: [Object],
                E17: [Object],
                F17: [Object],
                G17: [Object],
                H17: [Object],
                I17: [Object],
                J17: [Object],
                K17: [Object],
                A18: [Object],
                B18: [Object],
                C18: [Object],
                D18: [Object],
                E18: [Object],
                F18: [Object],
                G18: [Object],
                H18: [Object],
                I18: [Object],
                J18: [Object],
                K18: [Object],
                A19: [Object],
                B19: [Object],
                C19: [Object],
                D19: [Object],
                E19: [Object],
                F19: [Object],
                G19: [Object],
                H19: [Object],
                I19: [Object],
                J19: [Object],
                K19: [Object],
                L19: [Object],
                A20: [Object],
                B20: [Object],
                C20: [Object],
                D20: [Object],
                E20: [Object],
                F20: [Object],
                G20: [Object],
                H20: [Object],
                I20: [Object],
                J20: [Object],
                K20: [Object],
                L20: [Object],
                A21: [Object],
                B21: [Object],
                C21: [Object],
                D21: [Object],
                E21: [Object],
                F21: [Object],
                G21: [Object],
                H21: [Object],
                I21: [Object],
                J21: [Object],
                K21: [Object],
                L21: [Object],
                A22: [Object],
                B22: [Object],
                C22: [Object],
                D22: [Object],
                E22: [Object],
                F22: [Object],
                G22: [Object],
                H22: [Object],
                I22: [Object],
                J22: [Object],
                K22: [Object],
                A23: [Object],
                B23: [Object],
                C23: [Object],
                D23: [Object],
                E23: [Object],
                F23: [Object],
                G23: [Object],
                H23: [Object],
                I23: [Object],
                J23: [Object],
                K23: [Object],
                A24: [Object],
                B24: [Object],
                C24: [Object],
                D24: [Object],
                E24: [Object],
                F24: [Object],
                G24: [Object],
                H24: [Object],
                I24: [Object],
                J24: [Object],
                K24: [Object],
                A25: [Object],
                B25: [Object],
                C25: [Object],
                D25: [Object],
                E25: [Object],
                F25: [Object],
                G25: [Object],
                H25: [Object],
                I25: [Object],
                J25: [Object],
                K25: [Object],
                A26: [Object],
                B26: [Object],
                C26: [Object],
                D26: [Object],
                E26: [Object],
                F26: [Object],
                G26: [Object],
                H26: [Object],
                I26: [Object],
                J26: [Object],
                K26: [Object],
                A27: [Object],
                B27: [Object],
                C27: [Object],
                D27: [Object],
                E27: [Object],
                F27: [Object],
                G27: [Object],
                H27: [Object],
                I27: [Object],
                J27: [Object],
                K27: [Object],
                A28: [Object],
                B28: [Object],
                C28: [Object],
                D28: [Object],
                E28: [Object],
                F28: [Object],
                G28: [Object],
                H28: [Object],
                I28: [Object],
                J28: [Object],
                K28: [Object],
                A29: [Object],
                B29: [Object],
                C29: [Object],
                D29: [Object],
                E29: [Object],
                F29: [Object],
                G29: [Object],
                H29: [Object],
                I29: [Object],
                J29: [Object],
                K29: [Object],
                A30: [Object],
                B30: [Object],
                C30: [Object],
                D30: [Object],
                E30: [Object],
                F30: [Object],
                G30: [Object],
                H30: [Object],
                I30: [Object],
                J30: [Object],
                K30: [Object],
                A31: [Object],
                B31: [Object],
                C31: [Object],
                D31: [Object],
                E31: [Object],
                F31: [Object],
                G31: [Object],
                H31: [Object],
                I31: [Object],
                J31: [Object],
                K31: [Object],
                L31: [Object],
                A32: [Object],
                B32: [Object],
                C32: [Object],
                D32: [Object],
                E32: [Object],
                F32: [Object],
                G32: [Object],
                H32: [Object],
                I32: [Object],
                J32: [Object],
                K32: [Object],
                L32: [Object],
                A33: [Object],
                B33: [Object],
                C33: [Object],
                D33: [Object],
                E33: [Object],
                F33: [Object],
                G33: [Object],
                H33: [Object],
                I33: [Object],
                J33: [Object],
                K33: [Object],
                L33: [Object],
                A34: [Object],
                B34: [Object],
                C34: [Object],
                D34: [Object],
                E34: [Object],
                F34: [Object],
                G34: [Object],
                H34: [Object],
                I34: [Object],
                J34: [Object],
                K34: [Object],
                A35: [Object],
                B35: [Object],
                C35: [Object],
                D35: [Object],
                E35: [Object],
                F35: [Object],
                G35: [Object],
                H35: [Object],
                I35: [Object],
                J35: [Object],
                K35: [Object],
                A36: [Object],
                B36: [Object],
                C36: [Object],
                D36: [Object],
                E36: [Object],
                F36: [Object],
                G36: [Object],
                H36: [Object],
                I36: [Object],
                J36: [Object],
                K36: [Object],
                A37: [Object],
                B37: [Object],
                C37: [Object],
                D37: [Object],
                E37: [Object],
                F37: [Object],
                G37: [Object],
                H37: [Object],
                I37: [Object],
                J37: [Object],
                K37: [Object],
                L37: [Object],
                A38: [Object],
                B38: [Object],
                C38: [Object],
                D38: [Object],
                E38: [Object],
                F38: [Object],
                G38: [Object],
                H38: [Object],
                I38: [Object],
                J38: [Object],
                K38: [Object],
                L38: [Object],
                A39: [Object],
                B39: [Object],
                C39: [Object],
                D39: [Object],
                E39: [Object],
                F39: [Object],
                G39: [Object],
                H39: [Object],
                I39: [Object],
                J39: [Object],
                K39: [Object],
                L39: [Object],
                A40: [Object],
                B40: [Object],
                C40: [Object],
                D40: [Object],
                E40: [Object],
                F40: [Object],
                G40: [Object],
                H40: [Object],
                I40: [Object],
                J40: [Object],
                K40: [Object],
                L40: [Object],
                A41: [Object],
                B41: [Object],
                C41: [Object],
                D41: [Object],
                E41: [Object],
                F41: [Object],
                G41: [Object],
                H41: [Object],
                I41: [Object],
                J41: [Object],
                K41: [Object],
                L41: [Object],
                A42: [Object],
                B42: [Object],
                C42: [Object],
                D42: [Object],
                E42: [Object],
                F42: [Object],
                G42: [Object],
                H42: [Object],
                I42: [Object],
                J42: [Object],
                K42: [Object],
                L42: [Object],
                A43: [Object],
                B43: [Object],
                C43: [Object],
                D43: [Object],
                E43: [Object],
                F43: [Object],
                G43: [Object],
                H43: [Object],
                I43: [Object],
                J43: [Object],
                K43: [Object],
                A44: [Object],
                B44: [Object],
                C44: [Object],
                D44: [Object],
                E44: [Object],
                F44: [Object],
                G44: [Object],
                H44: [Object],
                I44: [Object],
                J44: [Object],
                K44: [Object],
                A45: [Object],
                B45: [Object],
                C45: [Object],
                D45: [Object],
                E45: [Object],
                F45: [Object],
                G45: [Object],
                H45: [Object],
                I45: [Object],
                J45: [Object],
                K45: [Object],
                A46: [Object],
                B46: [Object],
                C46: [Object],
                D46: [Object],
                E46: [Object],
                F46: [Object],
                G46: [Object],
                H46: [Object],
                I46: [Object],
                J46: [Object],
                K46: [Object],
                L46: [Object],
                A47: [Object],
                B47: [Object],
                C47: [Object],
                D47: [Object],
                E47: [Object],
                F47: [Object],
                G47: [Object],
                H47: [Object],
                I47: [Object],
                J47: [Object],
                K47: [Object],
                L47: [Object],
                A48: [Object],
                B48: [Object],
                C48: [Object],
                D48: [Object],
                E48: [Object],
                F48: [Object],
                G48: [Object],
                H48: [Object],
                I48: [Object],
                J48: [Object],
                K48: [Object],
                A49: [Object],
                B49: [Object],
                C49: [Object],
                D49: [Object],
                E49: [Object],
                F49: [Object],
                G49: [Object],
                H49: [Object],
                I49: [Object],
                J49: [Object],
                K49: [Object],
                A50: [Object],
                B50: [Object],
                C50: [Object],
                D50: [Object],
                E50: [Object],
                F50: [Object],
                G50: [Object],
                H50: [Object],
                I50: [Object],
                J50: [Object],
                K50: [Object],
                A51: [Object],
                B51: [Object],
                C51: [Object],
                D51: [Object],
                E51: [Object],
                F51: [Object],
                G51: [Object],
                H51: [Object],
                I51: [Object],
                J51: [Object],
                K51: [Object],
                L51: [Object],
                A52: [Object],
                B52: [Object],
                C52: [Object],
                D52: [Object],
                E52: [Object],
                F52: [Object],
                G52: [Object],
                H52: [Object],
                I52: [Object],
                J52: [Object],
                K52: [Object],
                L52: [Object],
                A53: [Object],
                B53: [Object],
                C53: [Object],
                D53: [Object],
                E53: [Object],
                F53: [Object],
                G53: [Object],
                H53: [Object],
                I53: [Object],
                J53: [Object],
                K53: [Object],
                A54: [Object],
                B54: [Object],
                C54: [Object],
                D54: [Object],
                E54: [Object],
                F54: [Object],
                G54: [Object],
                H54: [Object],
                I54: [Object],
                J54: [Object],
                K54: [Object],
                A55: [Object],
                B55: [Object],
                C55: [Object],
                D55: [Object],
                E55: [Object],
                F55: [Object],
                G55: [Object],
                H55: [Object],
                I55: [Object],
                J55: [Object],
                K55: [Object],
                A56: [Object],
                B56: [Object],
                C56: [Object],
                D56: [Object],
                E56: [Object],
                F56: [Object],
                G56: [Object],
                H56: [Object],
                I56: [Object],
                J56: [Object],
                K56: [Object],
                A57: [Object],
                B57: [Object],
                C57: [Object],
                D57: [Object],
                E57: [Object],
                F57: [Object],
                G57: [Object],
                H57: [Object],
                I57: [Object],
                J57: [Object],
                K57: [Object],
                A58: [Object],
                B58: [Object],
                C58: [Object],
                D58: [Object],
                E58: [Object],
                F58: [Object],
                G58: [Object],
                H58: [Object],
                I58: [Object],
                J58: [Object],
                K58: [Object],
                A59: [Object],
                B59: [Object],
                C59: [Object],
                D59: [Object],
                E59: [Object],
                F59: [Object],
                G59: [Object],
                H59: [Object],
                I59: [Object],
                J59: [Object],
                K59: [Object],
                L59: [Object],
                A60: [Object],
                B60: [Object],
                C60: [Object],
                D60: [Object],
                E60: [Object],
                F60: [Object],
                G60: [Object],
                H60: [Object],
                I60: [Object],
                J60: [Object],
                K60: [Object],
                L60: [Object],
                A61: [Object],
                B61: [Object],
                C61: [Object],
                D61: [Object],
                E61: [Object],
                F61: [Object],
                G61: [Object],
                H61: [Object],
                I61: [Object],
                J61: [Object],
                K61: [Object],
                L61: [Object],
                A62: [Object],
                B62: [Object],
                C62: [Object],
                D62: [Object],
                E62: [Object],
                F62: [Object],
                G62: [Object],
                H62: [Object],
                I62: [Object],
                J62: [Object],
                K62: [Object],
                L62: [Object],
                A63: [Object],
                B63: [Object],
                C63: [Object],
                D63: [Object],
                E63: [Object],
                F63: [Object],
                G63: [Object],
                H63: [Object],
                I63: [Object],
                J63: [Object],
                K63: [Object],
                A64: [Object],
                B64: [Object],
                C64: [Object],
                D64: [Object],
                E64: [Object],
                F64: [Object],
                G64: [Object],
                H64: [Object],
                I64: [Object],
                J64: [Object],
                K64: [Object],
                A65: [Object],
                B65: [Object],
                C65: [Object],
                D65: [Object],
                E65: [Object],
                F65: [Object],
                G65: [Object],
                H65: [Object],
                I65: [Object],
                J65: [Object],
                K65: [Object],
                A66: [Object],
                B66: [Object],
                C66: [Object],
                D66: [Object],
                E66: [Object],
                F66: [Object],
                G66: [Object],
                H66: [Object],
                I66: [Object],
                J66: [Object],
                K66: [Object],
                L66: [Object],
                A67: [Object],
                B67: [Object],
                C67: [Object],
                D67: [Object],
                E67: [Object],
                F67: [Object],
                G67: [Object],
                H67: [Object],
                I67: [Object],
                J67: [Object],
                K67: [Object],
                A68: [Object],
                B68: [Object],
                C68: [Object],
                D68: [Object],
                E68: [Object],
                F68: [Object],
                G68: [Object],
                H68: [Object],
                I68: [Object],
                J68: [Object],
                K68: [Object],
                A69: [Object],
                B69: [Object],
                C69: [Object],
                D69: [Object],
                E69: [Object],
                F69: [Object],
                G69: [Object],
                H69: [Object],
                I69: [Object],
                J69: [Object],
                K69: [Object],
                A70: [Object],
                B70: [Object],
                C70: [Object],
                D70: [Object],
                E70: [Object],
                F70: [Object],
                G70: [Object],
                H70: [Object],
                I70: [Object],
                J70: [Object],
                K70: [Object],
                A71: [Object],
                B71: [Object],
                C71: [Object],
                D71: [Object],
                E71: [Object],
                F71: [Object],
                G71: [Object],
                H71: [Object],
                I71: [Object],
                J71: [Object],
                K71: [Object],
                A72: [Object],
                B72: [Object],
                C72: [Object],
                D72: [Object],
                E72: [Object],
                F72: [Object],
                G72: [Object],
                H72: [Object],
                I72: [Object],
                J72: [Object],
                K72: [Object],
                A73: [Object],
                B73: [Object],
                C73: [Object],
                D73: [Object],
                E73: [Object],
                F73: [Object],
                G73: [Object],
                H73: [Object],
                I73: [Object],
                J73: [Object],
                K73: [Object],
                A74: [Object],
                B74: [Object],
                C74: [Object],
                D74: [Object],
                E74: [Object],
                F74: [Object],
                G74: [Object],
                H74: [Object],
                I74: [Object],
                J74: [Object],
                K74: [Object],
                L74: [Object],
                A75: [Object],
                B75: [Object],
                C75: [Object],
                D75: [Object],
                E75: [Object],
                F75: [Object],
                G75: [Object],
                H75: [Object],
                I75: [Object],
                J75: [Object],
                K75: [Object],
                L75: [Object],
                A76: [Object],
                B76: [Object],
                C76: [Object],
                D76: [Object],
                E76: [Object],
                F76: [Object],
                G76: [Object],
                H76: [Object],
                I76: [Object],
                J76: [Object],
                K76: [Object],
                A77: [Object],
                B77: [Object],
                C77: [Object],
                D77: [Object],
                E77: [Object],
                F77: [Object],
                G77: [Object],
                H77: [Object],
                I77: [Object],
                J77: [Object],
                K77: [Object],
                A78: [Object],
                B78: [Object],
                C78: [Object],
                D78: [Object],
                E78: [Object],
                F78: [Object],
                G78: [Object],
                H78: [Object],
                I78: [Object],
                J78: [Object],
                K78: [Object],
                A79: [Object],
                B79: [Object],
                C79: [Object],
                D79: [Object],
                E79: [Object],
                F79: [Object],
                G79: [Object],
                H79: [Object],
                I79: [Object],
                J79: [Object],
                K79: [Object],
                A80: [Object],
                B80: [Object],
                C80: [Object],
                D80: [Object],
                E80: [Object],
                F80: [Object],
                G80: [Object],
                H80: [Object],
                I80: [Object],
                J80: [Object],
                K80: [Object],
                A81: [Object],
                B81: [Object],
                C81: [Object],
                D81: [Object],
                E81: [Object],
                F81: [Object],
                G81: [Object],
                H81: [Object],
                I81: [Object],
                J81: [Object],
                K81: [Object],
                A82: [Object],
                B82: [Object],
                C82: [Object],
                D82: [Object],
                E82: [Object],
                F82: [Object],
                G82: [Object],
                H82: [Object],
                I82: [Object],
                J82: [Object],
                K82: [Object],
                A84: [Object],
                A85: [Object],
                B85: [Object],
                C85: [Object],
                D85: [Object],
                E85: [Object],
                F85: [Object],
                G85: [Object],
                H85: [Object],
                I85: [Object],
                J85: [Object],
                K85: [Object],
                A86: [Object],
                B86: [Object],
                C86: [Object],
                D86: [Object],
                E86: [Object],
                F86: [Object],
                G86: [Object],
                H86: [Object],
                I86: [Object],
                J86: [Object],
                K86: [Object],
                A87: [Object],
                B87: [Object],
                C87: [Object],
                D87: [Object],
                E87: [Object],
                F87: [Object],
                G87: [Object],
                H87: [Object],
                I87: [Object],
                J87: [Object],
                K87: [Object],
                A88: [Object],
                B88: [Object],
                C88: [Object],
                D88: [Object],
                E88: [Object],
                F88: [Object],
                G88: [Object],
                H88: [Object],
                I88: [Object],
                J88: [Object],
                K88: [Object],
                A89: [Object],
                B89: [Object],
                C89: [Object],
                D89: [Object],
                E89: [Object],
                F89: [Object],
                G89: [Object],
                H89: [Object],
                I89: [Object],
                J89: [Object],
                K89: [Object],
                A90: [Object],
                B90: [Object],
                C90: [Object],
                D90: [Object],
                E90: [Object],
                F90: [Object],
                G90: [Object],
                H90: [Object],
                I90: [Object],
                J90: [Object],
                K90: [Object],
                A91: [Object],
                B91: [Object],
                C91: [Object],
                D91: [Object],
                E91: [Object],
                F91: [Object],
                G91: [Object],
                H91: [Object],
                I91: [Object],
                J91: [Object],
                K91: [Object],
                A92: [Object],
                B92: [Object],
                C92: [Object],
                D92: [Object],
                E92: [Object],
                F92: [Object],
                G92: [Object],
                H92: [Object],
                I92: [Object],
                J92: [Object],
                K92: [Object],
                L92: [Object],
                A93: [Object],
                B93: [Object],
                C93: [Object],
                D93: [Object],
                E93: [Object],
                F93: [Object],
                G93: [Object],
                H93: [Object],
                I93: [Object],
                J93: [Object],
                K93: [Object],
                L93: [Object],
                A94: [Object],
                B94: [Object],
                C94: [Object],
                D94: [Object],
                E94: [Object],
                F94: [Object],
                G94: [Object],
                H94: [Object],
                I94: [Object],
                J94: [Object],
                K94: [Object],
                A95: [Object],
                B95: [Object],
                C95: [Object],
                D95: [Object],
                E95: [Object],
                F95: [Object],
                G95: [Object],
                H95: [Object],
                I95: [Object],
                J95: [Object],
                K95: [Object],
                A96: [Object],
                B96: [Object],
                C96: [Object],
                D96: [Object],
                E96: [Object],
                F96: [Object],
                G96: [Object],
                H96: [Object],
                I96: [Object],
                J96: [Object],
                K96: [Object],
                A97: [Object],
                B97: [Object],
                C97: [Object],
                D97: [Object],
                E97: [Object],
                F97: [Object],
                G97: [Object],
                H97: [Object],
                I97: [Object],
                J97: [Object],
                K97: [Object],
                A98: [Object],
                B98: [Object],
                C98: [Object],
                D98: [Object],
                E98: [Object],
                F98: [Object],
                G98: [Object],
                H98: [Object],
                I98: [Object],
                J98: [Object],
                K98: [Object],
                A99: [Object],
                B99: [Object],
                C99: [Object],
                D99: [Object],
                E99: [Object],
                F99: [Object],
                G99: [Object],
                H99: [Object],
                I99: [Object],
                J99: [Object],
                K99: [Object],
                A100: [Object],
                B100: [Object],
                C100: [Object],
                D100: [Object],
                E100: [Object],
                F100: [Object],
                G100: [Object],
                H100: [Object],
                I100: [Object],
                J100: [Object],
                K100: [Object],
                A101: [Object],
                B101: [Object],
                C101: [Object],
                D101: [Object],
                E101: [Object],
                F101: [Object],
                G101: [Object],
                H101: [Object],
                I101: [Object],
                J101: [Object],
                K101: [Object],
                A102: [Object],
                B102: [Object],
                C102: [Object],
                D102: [Object],
                E102: [Object],
                F102: [Object],
                G102: [Object],
                H102: [Object],
                I102: [Object],
                J102: [Object],
                K102: [Object],
                A103: [Object],
                B103: [Object],
                C103: [Object],
                D103: [Object],
                E103: [Object],
                F103: [Object],
                G103: [Object],
                H103: [Object],
                I103: [Object],
                J103: [Object],
                K103: [Object],
                L103: [Object],
                A104: [Object],
                B104: [Object],
                C104: [Object],
                D104: [Object],
                E104: [Object],
                F104: [Object],
                G104: [Object],
                H104: [Object],
                I104: [Object],
                J104: [Object],
                K104: [Object],
                A105: [Object],
                B105: [Object],
                C105: [Object],
                D105: [Object],
                E105: [Object],
                F105: [Object],
                G105: [Object],
                H105: [Object],
                I105: [Object],
                J105: [Object],
                K105: [Object],
                L105: [Object],
                A106: [Object],
                B106: [Object],
                C106: [Object],
                D106: [Object],
                E106: [Object],
                F106: [Object],
                G106: [Object],
                H106: [Object],
                I106: [Object],
                J106: [Object],
                K106: [Object],
                '!autofilter': [Object],
                '!margins': [Object],
                '!merges': [Array]
        },
        Blatt1: {
            '!ref': 'B3:C10',
                B3: [Object],
                C3: [Object],
                B4: [Object],
                C4: [Object],
                B5: [Object],
                C5: [Object],
                B6: [Object],
                C6: [Object],
                B7: [Object],
                C7: [Object],
                B8: [Object],
                C8: [Object],
                B9: [Object],
                C9: [Object],
                B10: [Object],
                C10: [Object],
                '!margins': [Object]
        }
    },
    SheetNames: [ 'Tabelle1', 'Blatt1' ],
        Strings: [
    { t: 'Sem. von', r: '<t>Sem. von</t>', h: 'Sem. von' },
    { t: 'Sem. bis', r: '<t>Sem. bis</t>', h: 'Sem. bis' },
    { t: 'LV Name', r: '<t>LV Name</t>', h: 'LV Name' },
    { t: 'SWS', r: '<t>SWS</t>', h: 'SWS' },
    { t: 'Art', r: '<t>Art</t>', h: 'Art' },
    { t: 'Zug / Gruppe', r: '<t>Zug / Gruppe</t>', h: 'Zug / Gruppe' },
    { t: 'TN', r: '<t>TN</t>', h: 'TN' },
    { t: 'Dozentname', r: '<t>Dozentname</t>', h: 'Dozentname' },
    {
        t: 'Dozentvorname',
        r: '<t>Dozentvorname</t>',
        h: 'Dozentvorname'
    },
    { t: 'Status', r: '<t>Status</t>', h: 'Status' },
    { t: 'SWS-Dozent', r: '<t>SWS-Dozent</t>', h: 'SWS-Dozent' },
    { t: 'Vergütung', r: '<t>Vergütung</t>', h: 'Vergütung' },
    { t: 'SU', r: '<t>SU</t>', h: 'SU' },
    { t: '1. Zug', r: '<t>1. Zug</t>', h: '1. Zug' },
    { t: 'P', r: '<t>P</t>', h: 'P' },
    { t: 'Ü', r: '<t>Ü</t>', h: 'Ü' },
    {
        t: '1. Zug 2. Gruppe',
        r: '<t>1. Zug 2. Gruppe</t>',
        h: '1. Zug 2. Gruppe'
    },
    {
        t: '1. Zug 1. Gruppe',
        r: '<t>1. Zug 1. Gruppe</t>',
        h: '1. Zug 1. Gruppe'
    },
    { t: 'LB', r: '<t>LB</t>', h: 'LB' },
    { t: 'Projekt', r: '<t>Projekt</t>', h: 'Projekt' },
    { t: 'Gruppe A', r: '<t>Gruppe A</t>', h: 'Gruppe A' },
    {
        t: 'B1 Informatik 1',
        r: '<t>B1 Informatik 1</t>',
        h: 'B1 Informatik 1'
    },
    { t: 'Kleinen', r: '<t>Kleinen</t>', h: 'Kleinen' },
    { t: 'Barne', r: '<t>Barne</t>', h: 'Barne' },
    { t: 'Fernsel', r: '<t>Fernsel</t>', h: 'Fernsel' },
    { t: 'Linda', r: '<t>Linda</t>', h: 'Linda' },
    {
        t: 'B2 Computersysteme',
        r: '<t>B2 Computersysteme</t>',
        h: 'B2 Computersysteme'
    },
    { t: 'Müller', r: '<t>Müller</t>', h: 'Müller' },
    { t: 'Henning', r: '<t>Henning</t>', h: 'Henning' },
    { t: 'Selmanagic', r: '<t>Selmanagic</t>', h: 'Selmanagic' },
    { t: 'André', r: '<t>André</t>', h: 'André' },
    {
        t: 'B3 Propadeutikum und Medientheorie',
        r: '<t>B3 Propadeutikum und Medientheorie</t>',
        h: 'B3 Propadeutikum und Medientheorie'
    },
    { t: 'Frieß', r: '<t>Frieß</t>', h: 'Frieß' },
    { t: 'Regina', r: '<t>Regina</t>', h: 'Regina' },
    {
        t: 'B4 Mathematik fur Medieninformatik I',
        r: '<t>B4 Mathematik fur Medieninformatik I</t>',
        h: 'B4 Mathematik fur Medieninformatik I'
    },
    { t: 'Vigerske', r: '<t>Vigerske</t>', h: 'Vigerske' },
    { t: 'Dorothea', r: '<t>Dorothea</t>', h: 'Dorothea' },
    {
        t: 'B5 Grundlagen der Webprogrammierung',
        r: '<t>B5 Grundlagen der Webprogrammierung</t>',
        h: 'B5 Grundlagen der Webprogrammierung'
    },
    { t: 'Strippgen', r: '<t>Strippgen</t>', h: 'Strippgen' },
    { t: 'David', r: '<t>David</t>', h: 'David' },
    {
        t: 'B10 Mathematik fur Medieninformatik 2',
        r: '<t>B10 Mathematik fur Medieninformatik 2</t>',
        h: 'B10 Mathematik fur Medieninformatik 2'
    },
    { t: 'Thiel', r: '<t>Thiel</t>', h: 'Thiel' },
    { t: 'Hermann', r: '<t>Hermann</t>', h: 'Hermann' },
    {
        t: 'B11 Medienwirtschaft',
        r: '<t>B11 Medienwirtschaft</t>',
        h: 'B11 Medienwirtschaft'
    },
    {
        t: 'B7 Informatik 2',
        r: '<t>B7 Informatik 2</t>',
        h: 'B7 Informatik 2'
    },
    { t: 'Weber-Wulff', r: '<t>Weber-Wulff</t>', h: 'Weber-Wulff' },
    { t: 'Debora', r: '<t>Debora</t>', h: 'Debora' },
    {
        t: 'B8 Grundlagen Digitaler Medien',
        r: '<t>B8 Grundlagen Digitaler Medien</t>',
        h: 'B8 Grundlagen Digitaler Medien'
    },
    { t: 'Barthel', r: '<t>Barthel</t>', h: 'Barthel' },
    { t: 'Kai-Uwe', r: '<t>Kai-Uwe</t>', h: 'Kai-Uwe' },
    { t: 'Schall', r: '<t>Schall</t>', h: 'Schall' },
    { t: 'Konstantin', r: '<t>Konstantin</t>', h: 'Konstantin' },
    { t: 'B9 Netzwerke', r: '<t>B9 Netzwerke</t>', h: 'B9 Netzwerke' },
    { t: 'Sabri', r: '<t>Sabri</t>', h: 'Sabri' },
    { t: 'Peggy', r: '<t>Peggy</t>', h: 'Peggy' },
    { t: 'Riesland', r: '<t>Riesland</t>', h: 'Riesland' },
    { t: 'Mark', r: '<t>Mark</t>', h: 'Mark' },
    {
        t: 'B13 Bildverarbeitung',
        r: '<t>B13 Bildverarbeitung</t>',
        h: 'B13 Bildverarbeitung'
    },
    { t: 'Jung', r: '<t>Jung</t>', h: 'Jung' },
    { t: 'Klaus', r: '<t>Klaus</t>', h: 'Klaus' },
    {
        t: 'B14 Datenbanken',
        r: '<t>B14 Datenbanken</t>',
        h: 'B14 Datenbanken'
    },
    { t: 'Oßwald', r: '<t>Oßwald</t>', h: 'Oßwald' },
    { t: 'Rüger', r: '<t>Rüger</t>', h: 'Rüger' },
    {
        t: 'B15 Informatik 3',
        r: '<t>B15 Informatik 3</t>',
        h: 'B15 Informatik 3'
    },
    {
        t: 'B17 Computergrafik',
        r: '<t>B17 Computergrafik</t>',
        h: 'B17 Computergrafik'
    },
    { t: 'Lenz', r: '<t>Lenz</t>', h: 'Lenz' },
    { t: 'Tobias', r: '<t>Tobias</t>', h: 'Tobias' },
    {
        t: 'B18 3D-Design',
        r: '<t>B18 3D-Design</t>',
        h: 'B18 3D-Design'
    },
    { t: 'Thünen', r: '<t>Thünen</t>', h: 'Thünen' },
    { t: 'Jens von', r: '<t>Jens von</t>', h: 'Jens von' },
    {
        t: 'B19 Internationale Medienwirtschaft und Kommunikation',
        r: '<t>B19 Internationale Medienwirtschaft und Kommunikation</t>',
        h: 'B19 Internationale Medienwirtschaft und Kommunikation'
    },
    {
        t: 'B20.1 Auswertungen von Erfahrungen am Praxisplatz',
        r: '<t>B20.1 Auswertungen von Erfahrungen am Praxisplatz</t>',
        h: 'B20.1 Auswertungen von Erfahrungen am Praxisplatz'
    },
    { t: 'Gerbracht', r: '<t>Gerbracht</t>', h: 'Gerbracht' },
    {
        t: 'Eberhard H.-A.',
        r: '<t>Eberhard H.-A.</t>',
        h: 'Eberhard H.-A.'
    },
    {
        t: 'B24.1 Praxisphase 2: Praxisprojekt',
        r: '<t>B24.1 Praxisphase 2: Praxisprojekt</t>',
        h: 'B24.1 Praxisphase 2: Praxisprojekt'
    },
    { t: 'Gruppe B', r: '<t>Gruppe B</t>', h: 'Gruppe B' },
    { t: 'Gruppe C', r: '<t>Gruppe C</t>', h: 'Gruppe C' },
    { t: 'Steinicke', r: '<t>Steinicke</t>', h: 'Steinicke' },
    { t: 'Martin', r: '<t>Martin</t>', h: 'Martin' },
    { t: 'Gruppe D', r: '<t>Gruppe D</t>', h: 'Gruppe D' },
    { t: 'Koschnick', r: '<t>Koschnick</t>', h: 'Koschnick' },
    { t: 'Gruppe E', r: '<t>Gruppe E</t>', h: 'Gruppe E' },
    { t: 'Thumfart', r: '<t>Thumfart</t>', h: 'Thumfart' },
    { t: 'Maximilian', r: '<t>Maximilian</t>', h: 'Maximilian' },
    { t: 'Gruppe F', r: '<t>Gruppe F</t>', h: 'Gruppe F' },
    { t: 'Mochól', r: '<t>Mochól</t>', h: 'Mochól' },
    { t: 'Malgorzata', r: '<t>Malgorzata</t>', h: 'Malgorzata' },
    {
        t: 'B24.2 Projektmanagement',
        r: '<t>B24.2 Projektmanagement</t>',
        h: 'B24.2 Projektmanagement'
    },
    { t: 'Metzner', r: '<t>Metzner</t>', h: 'Metzner' },
    { t: 'Carolin', r: '<t>Carolin</t>', h: 'Carolin' },
    {
        t: 'GT2 Game Engines',
        r: '<t>GT2 Game Engines</t>',
        h: 'GT2 Game Engines'
    },
    { t: 'Schmelter', r: '<t>Schmelter</t>', h: 'Schmelter' },
    { t: 'Thereza', r: '<t>Thereza</t>', h: 'Thereza' },
    {
        t: 'GTAT2 Game Technology & Interactive Systems  Aktuelle Themen 2 - Raytracing',
        r: '<t>GTAT2 Game Technology &amp; Interactive Systems  Aktuelle Themen 2 - Raytracing</t>',
        h: 'GTAT2 Game Technology &amp; Interactive Systems  Aktuelle Themen 2 - Raytracing'
    },
    {
        t: 'GTAT2 Game Technology & Interactive Systems  Aktuelle Themen 2',
        r: '<t>GTAT2 Game Technology &amp; Interactive Systems  Aktuelle Themen 2</t>',
        h: 'GTAT2 Game Technology &amp; Interactive Systems  Aktuelle Themen 2'
    },
    {
        t: 'VC2 Bildanalyse',
        r: '<t>VC2 Bildanalyse</t>',
        h: 'VC2 Bildanalyse'
    },
    { t: 'Hezel', r: '<t>Hezel</t>', h: 'Hezel' },
    { t: 'Nico', r: '<t>Nico</t>', h: 'Nico' },
    {
        t: 'VCAT2 Visual Computing  Aktuelle Themen 2 - Applikationsentwicklung unter iOS',
        r: '<t>VCAT2 Visual Computing  Aktuelle Themen 2 - Applikationsentwicklung unter iOS</t>',
        h: 'VCAT2 Visual Computing  Aktuelle Themen 2 - Applikationsentwicklung unter iOS'
    },
    {
        t: 'WT2 Usability',
        r: '<t>WT2 Usability</t>',
        h: 'WT2 Usability'
    },
    ... 33 more items,
    Count: '639',
    Unique: '133'
],
    Styles: {
        Fonts: [
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object]
        ],
            Fills: [ [Object], [Object], [Object] ],
            Borders: [ {}, {} ],
            CellXf: [
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object], [Object],
            [Object]
        ]
    },
    Themes: {},
    SSF: {
        '0': 'General',
            '1': '0',
            '2': '0.00',
            '3': '#,##0',
            '4': '#,##0.00',
            '9': '0%',
            '10': '0.00%',
            '11': '0.00E+00',
            '12': '# ?/?',
            '13': '# ??/??',
            '14': 'm/d/yy',
            '15': 'd-mmm-yy',
            '16': 'd-mmm',
            '17': 'mmm-yy',
            '18': 'h:mm AM/PM',
            '19': 'h:mm:ss AM/PM',
            '20': 'h:mm',
            '21': 'h:mm:ss',
            '22': 'm/d/yy h:mm',
            '37': '#,##0 ;(#,##0)',
            '38': '#,##0 ;[Red](#,##0)',
            '39': '#,##0.00;(#,##0.00)',
            '40': '#,##0.00;[Red](#,##0.00)',
            '45': 'mm:ss',
            '46': '[h]:mm:ss',
            '47': 'mmss.0',
            '48': '##0.0E+0',
            '49': '@',
            '56': '"上午/下午 "hh"時"mm"分"ss"秒 "',
            '65535': 'General'
    }
}

Process finished with exit code 0
